name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.11.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: xvfb-run -a pnpm run test
        if: runner.os == 'Linux'

      - run: pnpm run test
        if: runner.os == 'macOS'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: runner.os != 'Linux'
