name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: ./node_modules/.bin/electron-rebuild --version 11.2.1
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm run coverage
        if: runner.os != 'Linux'

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./out/coverage/lcov.info
